### ISSUE TITLE
is final needed?

### ISSUE THREAD

**Issue by juliangut** [doctrine/couchdb-odm#141]
https://github.com/doctrine/couchdb-odm/blob/master/lib/Doctrine/ODM/CouchDB/DocumentRepository.php#L102

**Comment by Ocramius** [comment]
The entire class should probably be `final`, but only the `refresh` method got added as `final` due to its out-of-interface signature, and the late addition. Due to BC compliance, it is no longer possible to make the class itself `final`.

If you aren't aware of the reasons, see:

 * http://ocramius.github.io/blog/when-to-declare-classes-final/#comment-3400988766
 * https://slamdunk.github.io/blog/when-to-declare-methods-final/
